/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Base: typeof import('./src/components/Base.vue')['default']
    Chat: typeof import('./src/components/Chat.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    Discovery: typeof import('./src/components/Discovery.vue')['default']
    FriendList: typeof import('./src/components/FriendList.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MainWrap: typeof import('./src/components/.vue')['default']
    MemberList: typeof import('./src/components/MemberList.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    MiddleBar: typeof import('./src/components/MiddleBar.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
    Prompt: typeof import('./src/components/Prompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    UserBar: typeof import('./src/components/UserBar.vue')['default']
    UserDetail: typeof import('./src/components/User/UserDetail.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
  }
}
